name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate snake
        id: snake-gif
        with:
          github_user_name: gilzon
        run: |
          python3 snake.py
          echo $(cat snake.txt) >> $GITHUB_ENV
          echo "data_output_name=data" >> $GITHUB_ENV

      - name: Show build status
        run: git status

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v8
        with:
          message: Add contribution graph with snake
          author_name: GitHub Actions
          author_email: actions@github.com
          signoff: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy changes to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
